<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>catch方法</title>
</head>
<body>
    <script>
        const p = new Promise((resolve, reject)=>{
            setTimeout(()=>{
                //设置p对象的状态为失败,并设置失败的值
                reject("出错啦!");
            }, 1000)
        });
        //通过 then方法的回调函数获取失败状态的值
        /*p.then(function(value){}, function(reason){
            console.error(reason);
        });*/
        
        //通过 catch方法获取失败状态的值
        p.catch(function(reason){
            console.warn(reason);
        });
    </script>
</body>
</html>